name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - "final-backend/**"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Pull Latest Code on VM
        run: |
          cd ~/final-backend
          git pull origin main

      - name: Install Dependencies
        run: |
          cd ~/final-backend
          npm install

      - name: Restart Backend
        run: |
          pm2 restart backend
